language: go
go:
  - 1.10
cache: yarn
services:
  - docker
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - make
  - goveralls -service=travis-ci -ignore="handlers/static.go,handlers/tmpls/tmpls.go"
  - make buildDockerImage 
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push mxschmitt/golang_url_shortener && docker push mxschmitt/golang_url_shortener:arm; fi'
deploy:
  provider: bintray
  user: mxschmitt
  file: "build/bintray.json"
  key:
    secure: "DI10OBnQmWPB76j31uDrb0gkv1eAkwBfk4xLC4xf7qHuAzqAOTVhmO9e/yCOVsUMzPH5Nxehfb/bsKL55Gx72+tbIdOTqNn5Tf9ZbxqpZ7UEs6JJUoiL2iU+CY5r4XJvM+0TtQxrOLFWKrRygIl81KHY9M/GMDwCQuVPAIebyquptya+w+CrckhR5k7jKDdFQZLWc6cOHLZ8+DDccv+hnQvypro7OahTF1Ehn3NCaTOLFkFB0pjXFtSqYSJJXJVj9dCEMcPccPMGc3MTkoYTyLmWXLoGELJphIftQXCoPL4BmJKzL12rk1+Vyx4I6hvdDOLiobNUE/LApBke77UkHpmzPWoD1ym2nkxVNAemCGcumn6kZK8K4VRQrA/OvM9i4kDFyFo8wOW8InQC39M1N0OcfQF9ZgktCD76E+AxVruashf9j9N0noBif0xbyCVu9kNn6uqFvKxTQPMtMSlS70NubOFQlmv/qSFfGSEyJ10p69b38DhQV1sLX/JgEbcOh45xazkDD+M8tRV9zCqEPs1wiE6Dx3Z/+5mM9hKkhNvF0pBIAkKiiBQoIcT/xO0i9+6hYww89/6My3eXaS6Ce/VszqV0tBHUY4Oh0AggxYR0JBAD7oK9g/utRQxljpmVK8C3Gq4LSJBXi+6isyX1m26DJu6XaDpa8iPkSr9UVyE="
env:
  global:
    secure: n+8G1Y52ijOL9xLJm/dO80F3VipkqovhMlE6NOkYBAjGLAzbvWuU1Qh/fCmMc/m2yNk5S/2jH3bIG/w/npLBjegqfIvBJhRvyGFUDdH1LiJ9P+oO+NYtNCQCLW8hIRs+tUi8XdOtxLVBP8h90RGKsP0zgycd+UX221u2CpBn2ogWDOwV9lo2Y/UQ0n8CTdRrVMtnx3XhHbL220PII6QTd/5wmP314HPbbp+9ihNCoyCLkHjSo+ZJ25NMO7rVsci91rfg6GJclWV6yd1LBMA5ofReJZkalZt6PK+yEO0+OIL7MaXscRe74EZxy7HJrKsSTTo57xttEmECNSlf/AM6LMqXRi8ble8ScEqhIW7H/FtXGiyTwueYSAsIKmNGnkx9eCxo/rsF/F3serLzffSzbdxFe1OyeAxZnsbhazA1Z+JnnjdhtieZ2mjeIZeDXfSTNF23Ul5wiS+eaopSWe0r+XdWUe/MrMUvyRFy9T6U4MmTWjiA7xf8HMUWScN981MgPrkmd3rfv/UnCt8xJ353UTCHqugQ+Y58SmGIN3CVLS/hGg8AGl/FSjbEEShZ5qS1bbNLI0++l0W2zDFRNtHsJw1E/byfUEFyfNpVzf/z3PYUm0YkK/mx5pIYDQSI2zLlggqsfy5yQQrdbgqzbk3ys2+8TM37BQxUjP6QLcVVUSk=