language: go
go:
  - 1.9.2
env:
  global:
    - COVERALLS_TOKEN=lhWzILT1WMRgrHXsEhauQOGsoby1nm7DR
script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN