golang_url_shortener:
  image: maxibanki/golang_url_shortener
  ports:
    - 8080:8080
  volumes:
    - ./data:/data
  environment:
    - GUS_BASE_URL=https://s.b0n.pl
    - GUS_GOOGLE_CLIENT_ID=
    - GUS_GOOGLE_CLIENT_SECRET=
    - GUS_GITHUB_CLIENT_ID=
    - GUS_GITHUB_CLIENT_SECRET=
    - GUS_MICROSOFT_CLIENT_ID=
    - GUS_MICROSOFT_CLIENT_SECRET=
  restart: always
